### ISSUE TITLE
Please clarify the license for this repo

### ISSUE THREAD

**Issue by mbrukman** [Const-me/Vrmac#2]
First of all, thank you for sharing this project with us!

**Disclaimer: I am not a lawyer, and this is not legal advice.**

That said, your repo appears to have two conflicting licenses:

* MIT license in [`LICENSE`][license] 
* Custom EULA in [`EULA.txt`][eula]

Either one is fine if that's what you would like, but together, they appear to conflict because `EULA.txt` has conditions above and beyond what the MIT license requires of users, so if one has to apply both licenses, the stricter one wins, and that means the EULA overrides the MIT license in this case, so this project is technically not MIT-licensed as it appears.

To clarify the situation, once you've decided on the license you'd like for your project is to replace the `LICENSE` file with just that license, and remove the `EULA.txt`. Either license is fine—it's your choice as the project author and copyright holder—but it would be good to avoid confusion for future users.

All the best with your project!

[license]: https://github.com/Const-me/Vrmac/blob/bbe83b9722dcb080f1aedfa0596541236f1299c7/LICENSE
[eula]: https://github.com/Const-me/Vrmac/blob/bbe83b9722dcb080f1aedfa0596541236f1299c7/EULA.txt

**Comment by Const-me** [comment]
@mbrukman MIT covers whatever source code is in the git portion of the repository.

EULA cover whatever I ship in binaries, that stuff in the release page of this github repository also on nuget.org.

Splitting them into 2 repositories with different licenses would be inconvenient for users, you need native DLLs to run that stuff. For me as well, the solution in this repo builds nuget packages I publish on nuget.org, EULA.txt needs to be included into these packages.
